In [11]:
import torch

X = torch.arange(12)
print(X.shape)
print(X)

torch.Size([12])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [13]:
print(X.reshape(2,6))

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [18]:
print(X.reshape(3,4))
print(X.shape)
print(X.numel())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([12])
12


In [17]:
print(X.shape)
print(X.numel())

torch.Size([12])
12


In [ ]:
print(X.reshape(3,-1))  #利用-1自动算出维度
print(X.reshape(-1,4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [22]:
print(torch.zeros((2,3,4)))
print(torch.ones((2,3,4)))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [ ]:
torch.randn(3,4)  #随机采样

tensor([[ 0.6332,  0.0324,  0.0601, -0.8618],
        [ 0.4802,  0.3203, -2.1122,  0.0363],
        [-0.2521, -0.5528,  1.3102, -0.1230]])

In [26]:
A = torch.tensor([
    [2,1],
    [3,1],
    [3,2]
])
print(A)
print(A.shape)

tensor([[2, 1],
        [3, 1],
        [3, 2]])
torch.Size([3, 2])


In [31]:
X = torch.arange(12,dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1 , 3, 4],[1, 2, 3, 4],[4, 3, 2, 1]])
print(torch.cat((X, Y), dim = 0))
print(torch.cat((X, Y), dim = 1))
print(X)
print(Y)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  3.,  4.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  3.,  4.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 3., 4.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


In [32]:
print(X == Y)

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [9]:
import torch
X = torch.arange(12,dtype=torch.float32).reshape(3,4)
print(X)
print(X[-1])
print(X[1:3])
X[1,2] = 9
print(X)
X[0:2,:] = 12
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


In [ ]:
Y = torch.ones(3,4)
X = torch.zeros(3,4)
Z = torch.zeros_like(Y)
print(id(Z))
Z[:] = X + Y    #节约内存
print(id(Z))

2176704631632
2176704631632


In [ ]:
A = torch.arange(20).reshape(4,5)
print(A)
print(A.T)  #A的转置

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])
