In [ ]:
import torch
x = torch.arange(40,dtype = torch.float32).reshape(5,8)
print(x)

x_sum_axis0 = x.sum(axis = 0)   #降维求和
print(x_sum_axis0)
print(x_sum_axis0.shape)
x_sum_axis1 = x.sum(axis = 1)
print(x_sum_axis1)
print(x_sum_axis1.shape)

x_sum_axis0_keepdims = x.sum(axis=0, keepdims=True) #非降维求和
print(x_sum_axis0_keepdims)
print(x_sum_axis0_keepdims.shape)
x_sum_axis1_keepdims = x.sum(axis=1, keepdims=True)
print(x_sum_axis1_keepdims)
print(x_sum_axis1_keepdims.shape)

print(x.cumsum(axis=0))     #cumsum函数不会沿任何轴降低维度
print(x.cumsum(axis=0).shape)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20., 21., 22., 23.],
        [24., 25., 26., 27., 28., 29., 30., 31.],
        [32., 33., 34., 35., 36., 37., 38., 39.]])
tensor([ 80.,  85.,  90.,  95., 100., 105., 110., 115.])
torch.Size([8])
tensor([ 28.,  92., 156., 220., 284.])
torch.Size([5])
tensor([[ 80.,  85.,  90.,  95., 100., 105., 110., 115.]])
torch.Size([1, 8])
tensor([[ 28.],
        [ 92.],
        [156.],
        [220.],
        [284.]])
torch.Size([5, 1])
tensor([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.],
        [  8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.],
        [ 24.,  27.,  30.,  33.,  36.,  39.,  42.,  45.],
        [ 48.,  52.,  56.,  60.,  64.,  68.,  72.,  76.],
        [ 80.,  85.,  90.,  95., 100., 105., 110., 115.]])
torch.Size([5, 8])


In [ ]:
import torch
A = torch.ones(4,dtype=torch.float32)       #点积
print(A)
X = torch.arange(4,dtype=torch.float32)
print(X)

print(torch.dot(A,X))

tensor([1., 1., 1., 1.])
tensor([0., 1., 2., 3.])
tensor(6.)
