In [2]:
import torch

#自动微分

x = torch.arange(4.0)
print(x)
print(x.shape)

x.requires_grad_(True)
print(x.grad)

y = 2 * torch.dot(x, x)

print(y)
print(y.shape)

y.backward()
print(x.grad)

print(x.grad == 4 * x)

x.grad.zero_()  #pytorch默认情况会自动累计梯度
y = x.sum()
y.backward
print(x.grad)

tensor([0., 1., 2., 3.])
torch.Size([4])
None
tensor(28., grad_fn=<MulBackward0>)
torch.Size([])
tensor([ 0.,  4.,  8., 12.])
tensor([True, True, True, True])
tensor([0., 0., 0., 0.])
